import streamlit as st
import numpy as np
import librosa
import io
import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial import distance

st.set_page_config(layout="wide", page_title="PneumaForensic")

@st.cache_data
def analyze_audio(y, sr, filename):
    duration = len(y) / sr
    events = []
    
    rms = librosa.feature.rms(y=y).flatten()
    times = librosa.frames_to_time(rms, sr=sr)
    thresh = np.percentile(rms, 80)
    peaks = np.where((rms > thresh) & (rms[1:-1] > rms[:-2]) & (rms[1:-1] > rms[2:]))[0] + 1
    events.extend(times[peaks])
    
    env = np.abs(y)
    env_smooth = np.convolve(env, np.ones(1000)/1000, mode='same')
    env_peaks = np.where((env_smooth > 2*np.mean(env_smooth)) & 
                        (env_smooth[1:-1] > env_smooth[:-2]) & 
                        (env_smooth[1:-1] > env_smooth[2:]))[0] + 1
    events.extend(env_peaks / sr)
    
    events = sorted(list(set(events)))
    final_events = []
    last_t = 0
    for t in events:
        if t > 1.0 and t - last_t > 0.8:
            final_events.append(t)
            last_t = t
    events = final_events[:12]
    
    if len(events) < 2:
        events = np.linspace(2, duration-2, 5).tolist()
    
    # DETAILED PARAMETERS
    ibis = np.diff(events)
    ibi_cv = np.std(ibis) / np.mean(ibis) if len(ibis)>0 else 0
    
    flatness = []
    for t in events[:4]:
        start = int(max(0, (t-0.15)*sr))
        end = int(min(len(y), (t+0.15)*sr))
        if end > start:
            flat = np.mean(librosa.feature.spectral_flatness(y=y[start:end]))
            flatness.append(flat)
    avg_flat = np.mean(flatness) if flatness else 0.6
    
    silence_std = np.std(y[np.abs(y) < 0.01])
    
    amps = [np.max(np.abs(y[int(max(0,(t-0.1)*sr)):int(min(len(y),(t+0.2)*sr))])) for t in events]
    amp_cv = np.std(amps)/np.mean(amps) if amps and np.mean(amps)>0 else 0
    
    # 6 PARAMETERS
    p1_timing = min(ibi_cv * 4, 1.0)      # Timing Regularity
    p2_purity = max((avg_flat - 0.2) * 4, 0)  # Spectral Purity
    p3_density = 1.0 if (len(events)/duration*60 < 10 or len(events)/duration*60 > 40) else 0.2  # Density
    p4_noise = max(1 - silence_std * 10000, 0)  # Noise Floor
    p5_amp = min(amp_cv * 3, 1.0)         # Amplitude Variation
    p6_sim = 0.5                           # Similarity
    
    score = p1_timing*0.28 + p2_purity*0.18 + p3_density*0.15 + p4_noise*0.15 + p5_amp*0.12 + p6_sim*0.12
    
    return score, events, {
        "File": filename,
        "AI": f"{score:.0%}",
        "Timing": f"{p1_timing:.0%}",
        "Purity": f"{p2_purity:.0%}",
        "Density": f"{p3_density:.0%}",
        "Noise": f"{p4_noise:.0%}",
        "AmpVar": f"{p5_amp:.0%}",
        "Sim": f"{p6_sim:.0%}",
        "Breaths": len(events)
    }

st.title("🫁 PneumaForensic")

with st.expander("📖 How to Read the Graph", expanded=False):
    st.markdown("""
    **Graph:**
    - **The Gray Waves**: The actual sound of the person speaking.
    - **The Red Dashed Lines**: These mark every time the AI detects a breath.
    
    **The Spacing:**
    - **Natural/Human**: The red lines appear at **uneven intervals**, showing the speaker paused naturally to catch their breath.
    - **Synthetic/AI**: The red lines look like a **perfectly timed grid**, or they are **missing entirely**, proving the voice was generated by a machine.
    """)

uploaded_files = st.file_uploader("Upload Audio Files", type=['wav','mp3','m4a'], accept_multiple_files=True)

if uploaded_files:
    col1, col2 = st.columns([1.2,1])
    
    with col1:
        st.subheader("📊 Forensic Results")
        results = []
        
    with col2:
        st.subheader("📈 Breath Patterns")
    
    for i, file in enumerate(uploaded_files):
        try:
            audio_bytes = file.read()
            y, sr = librosa.load(io.BytesIO(audio_bytes), sr=16000)
            
            score, events, metrics = analyze_audio(y, sr, file.name)
            results.append(metrics)
            
            # Graph
            fig, ax = plt.subplots(figsize=(8, 2.2))
            time_axis = np.linspace(0, len(y)/sr, len(y))
            ax.plot(time_axis, y, 'lightgray', alpha=0.7, lw=0.5)
            
            for j, t in enumerate(events):
                ax.axvline(t, color='red', lw=3, linestyle='--', alpha=0.9)
                ax.fill_betweenx([-0.4,0.4], t-0.08, t+0.08, color='red', alpha=0.25)
            
            color = 'red' if score > 0.6 else 'green'
            ax.text(0.02, 0.9, f"{score:.0%}", transform=ax.transAxes, fontsize=16, 
                   color=color, fontweight='bold', va='top')
            ax.text(0.02, 0.6, f"{len(events)} breaths", transform=ax.transAxes, fontsize=10, 
                   color='white', va='top')
            
            ax.set_facecolor('black')
            ax.set_xlim(0, min(len(y)/sr, 20))
            ax.axis('off')
            
            with col2:
                st.pyplot(fig)
                plt.close(fig)
            
        except:
            continue
    
    if results:
        with col1:
            df = pd.DataFrame(results)
            st.dataframe(df, use_container_width=True, height=500)

st.caption("🫁 6 Breathing Parameters: Timing(28%) Purity(18%) Density(15%) Noise(15%) AmpVar(12%) Sim(12%)")
